language: node_js
node_js:
  - "8"
  - "7"
before_install:  
  - npm install -g npm
script: 
  - npm run mocha-travis
cache:
  directories:
    - "node_modules"
after_success: 
  - npm run coveralls
notifications:
  email: false