language: node_js
services:
  - redis-server
node_js:
  - "9"
  - "8"
  - "10"
before_install:  
  - npm install -g npm
  - npm install -g codecov
script: 
  - npm run dev-travis
cache:
  directories:
    - "node_modules"
after_success: 
  - npm run coveralls
  - npm run codecov
notifications:
  email: false